const panels={media:{title:"Media",items:["Import videos","Import images","Recent media","Stock placeholders"]},audio:{title:"Audio",items:["Music","Sound effects","Voiceover","Extract audio"]},text:{title:"Text",items:["Add text","Text templates","Auto captions","Font styles"]},stickers:{title:"Stickers",items:["Emoji","Meme","Gaming","Shapes"]},effects:{title:"Effects",items:["Glitch","Shake","Glow","VHS","Flash","Blur"]},filters:{title:"Filters",items:["Original","Cinema","Retro","Cool","Warm","B&W"]},transitions:{title:"Transitions",items:["Fade","Slide","Zoom","Spin","Flash"]},captions:{title:"Captions",items:["Auto captions","Caption styles","Highlight words","Karaoke"]},adjust:{title:"Adjust",items:["Brightness","Contrast","Saturation","Sharpness","Temperature"]}};
const tools=document.querySelectorAll(".tool"), panelTitle=document.querySelector("#panelTitle"), content=document.querySelector("#panelContent");
function renderPanel(name){const p=panels[name];panelTitle.textContent=p.title;content.innerHTML="";if(name==="stickers"){const emojis=["😀","😂","😎","😭","💀","🔥","❤️","💯","👀","🤯","⭐","✨","💥","🎉","🎮","👑","🚀","💎","🗿","🤣","😱","🥶","😈","🤡"];const g=document.createElement("div");g.className="emoji-grid";emojis.forEach(e=>{const b=document.createElement("div");b.className="emoji";b.textContent=e;b.onclick=()=>addSticker(e);g.appendChild(b)});content.appendChild(g);return}p.items.forEach(x=>{const d=document.createElement("div");d.className="asset-card";d.textContent=x;d.onclick=()=>action(name,x);content.appendChild(d)})}
function action(panel,item){if(panel==="text"&&item==="Add text"){const t=prompt("Enter text");if(t)addText(t)}else if(panel==="media"&&item.startsWith("Import"))fileInput.click();else if(panel==="audio"&&item==="Voiceover"){alert("Voiceover recording is planned for the next build.")}else alert(item+" is ready for the next editing module.")}
function addText(t){overlayText.textContent=t;const c=document.createElement("div");c.className="clip text";c.textContent=t;textTrack.appendChild(c)}
function addSticker(e){overlayText.textContent=e;const c=document.createElement("div");c.className="clip text";c.textContent=e;textTrack.appendChild(c)}
tools.forEach(t=>t.onclick=()=>{tools.forEach(x=>x.classList.remove("active"));t.classList.add("active");renderPanel(t.dataset.panel)});
const fileInput=document.querySelector("#fileInput"),importBtn=document.querySelector("#importBtn"),video=document.querySelector("#video"),empty=document.querySelector("#emptyPreview"),play=document.querySelector("#play"),time=document.querySelector("#time"),duration=document.querySelector("#duration"),projectTime=document.querySelector("#projectTime"),videoTrack=document.querySelector("#videoTrack"),audioTrack=document.querySelector("#audioTrack"),textTrack=document.querySelector("#textTrack"),overlayText=document.querySelector("#overlayText");
importBtn.onclick=()=>fileInput.click();
fileInput.onchange=()=>[...fileInput.files].forEach(file=>{const url=URL.createObjectURL(file);const c=document.createElement("div");c.className="clip "+(file.type.startsWith("audio")?"audio":"video");c.textContent=file.name;(file.type.startsWith("audio")?audioTrack:videoTrack).appendChild(c);if(file.type.startsWith("video")){video.src=url;empty.style.display="none";video.load()}});
play.onclick=()=>video.paused?video.play():video.pause();
video.onplay=()=>play.textContent="❚❚";video.onpause=()=>play.textContent="▶";
function fmt(s){if(!isFinite(s))return"00:00";return String(Math.floor(s/60)).padStart(2,"0")+":"+String(Math.floor(s%60)).padStart(2,"0")}
video.ontimeupdate=()=>{time.textContent=fmt(video.currentTime);projectTime.textContent=fmt(video.currentTime)+" / "+fmt(video.duration)};
video.onloadedmetadata=()=>{duration.textContent=fmt(video.duration);projectTime.textContent="00:00 / "+fmt(video.duration)};
document.querySelector(".export").onclick=()=>alert("Export pipeline will use FFmpeg in the desktop build.");
document.querySelector("#addTrack").onclick=()=>alert("New timeline track created in the full desktop build.");
renderPanel("media");